### ISSUE TITLE
Code blocks do scroll

### ISSUE THREAD

**Issue by johnhenriksson** [thegeeklab/hugo-geekblog#506] opened 2024-02-18 13:05 UTC
I'm using theme version v0.2.6.1 and it does not work with horizontal scroll in code blocks

My blog is at https://nerd-geek.com/blog/2020/build-ubuntu-vm-with-packer-on-vsphere/

<img width="1197" alt="image" src="https://github.com/thegeeklab/hugo-geekblog/assets/10085800/17446747-3c48-4470-a120-f6f39860e646">

I'm using these settings in my hugo.toml file

```toml
# Geekblog required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 9
```

**Comment by xoxys** [comment] 2024-02-18 19:06
Thanks for your report. Are you really sure that you use the latest https://github.com/thegeeklab/hugo-geekblog/releases/tag/v0.26.1 release? Is the source of your blog publically available?

I'm currently not able to reproduce it:

![image](https://github.com/thegeeklab/hugo-geekblog/assets/3391958/1aefb728-c22c-444d-a460-bdff19a78d9c)

**Comment by johnhenriksson** [comment] 2024-02-19 07:58
Yes I use THEME_VERSION := v0.26.1

The code is public at https://github.com/johnhenriksson/johnhenrikssonblog 

I also have some strange styling on the code https://nerd-geek.com/blog/2021/deploy-k8s-vms-with-terraform-on-vsphere/

<img width="979" alt="image" src="https://github.com/thegeeklab/hugo-geekblog/assets/10085800/4b3ac104-8fbe-41c1-b050-90686946d0ca">

**Comment by xoxys** [comment] 2024-02-19 08:50
Thanks, found the issue. This looks like a weird hugo issue while loading the configuration... This change fixes the code block rendering:

```diff
diff --git a/hugo.toml b/hugo.toml
index 83b6bda..b4b4c30 100644
--- a/hugo.toml
+++ b/hugo.toml
@@ -5,10 +5,6 @@ theme = 'hugo-geekblog'
 sectionPagesMenu = 'main'
 googleAnalytics = "G-RHTJKJXTF6"
 
-[services]
-  [services.disqus]
-    shortname = 'nerd-geek'
-
 pluralizeListTitles = false
 
 # Geekblog required configuration
@@ -16,6 +12,10 @@ pygmentsUseClasses = true
 pygmentsCodeFences = true
 disablePathToLower = true
 
+[services]
+  [services.disqus]
+    shortname = 'nerd-geek'
+
 # Needed for mermaid shortcodes
 [markup]
   [markup.goldmark.renderer]
```

**Comment by johnhenriksson** [comment] 2024-02-19 14:16
If I load [service.disqus] after [markup] it seems to work!

**Comment by xoxys** [comment] 2024-04-10 07:32
I'm going to close this issue as solved. Please open a new one if you still have issues.

**Closed by xoxys** 2024-04-10 07:32 UTC
Labels: question
